# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoonMessenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoonMessenger
  pod 'SnapKit'
  pod 'Closures'
  pod 'Hero'
  pod 'Parse'
  pod 'lottie-ios'

end
